### ISSUE TITLE
**Build broken after #354/#355**  `bazelisk build //...` fails with undeclared identifiers in `dds_c_api.cpp`:

### ISSUE THREAD

**Issue by wopdevries** [dds-bridge/dds#360]
library/src/api/dds_c_api.cpp:261:16: error: use of undeclared identifier 'Par'
library/src/api/dds_c_api.cpp:275:16: error: use of undeclared identifier 'SidesPar'

Reproducible on clean develop (437e06da) with no local changes.

**Comment by krtschil** [comment]
Same as #359
